name: Main
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Sonar Analysis
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  check-paths:
    runs-on: ubuntu-latest
    needs: [sonar, tests]
    if: ${{ github.event_name != 'pull_request' }}
    name: Check Changes
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            core:
              - 'src/core/**'
            db:
              - 'src/db/decaf.db.common/**'
            npgsql:
              - 'src/db/decaf.npgsql/**'
            sqlserver:
              - 'src/db/decaf.sqlserver/**'
            sqlite:
              - 'src/db/decaf.sqlite/**'
            services:
              - 'src/extensions/decaf.services/**'
            logging_serilog:
              - 'src/extensions/decaf.logging.serilog/**'
    outputs:
      run-core: ${{ steps.changes.outputs.core }}
      run-db: ${{ steps.changes.outputs.db }}
      run-npgsql: ${{ steps.changes.outputs.npgsql }}
      run-sqlserver: ${{ steps.changes.outputs.sqlserver }}
      run-sqlite: ${{ steps.changes.outputs.sqlite }}
      run-services: ${{ steps.changes.outputs.services }}
      run-logging-serilog: ${{ steps.changes.outputs.logging_serilog }}

  pub-decaf:
    name: decaf
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-core == 'true' }}
    uses: ./.github/workflows/publish-decaf.yml
    secrets: inherit

  pub-decafdb:
    name: decaf.db
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-db == 'true' }}
    uses: ./.github/workflows/publish-decaf.db.yml
    secrets: inherit

  pub-decafnpgsql:
    name: decaf.npgsql
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-npgsql == 'true' }}
    uses: ./.github/workflows/publish-decaf.db.npgsql.yml
    secrets: inherit

  pub-decafsqlserver:
    name: decaf.sqlserver
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-sqlserver == 'true' }}
    uses: ./.github/workflows/publish-decaf.db.sqlserver.yml
    secrets: inherit
  
  pub-decafsqlite:
    name: decaf.sqlite
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-sqlite == 'true' }}
    uses: ./.github/workflows/publish-decaf.db.sqlite.yml
    secrets: inherit

  pub-decafservices:
    name: decaf.services
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-services == 'true' }}
    uses: ./.github/workflows/publish-decaf.services.yml
    secrets: inherit
  
  pub-decafloggingserilog:
    name: decaf.logging.serilog
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-logging-serilog == 'true' }}
    uses: ./.github/workflows/publish-decaf.logging.serilog.yml
    secrets: inherit
