name: Main
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Sonar Analysis
    uses: daniel-buchanan/pdq/.github/workflows/sonar.yml@main
    secrets: inherit
  
  tests:
    name: Run Tests
    uses: daniel-buchanan/pdq/.github/workflows/tests.yml@main
    secrets: inherit

  check-paths:
    runs-on: ubuntu-latest
    needs: [sonar, tests]
    name: Check Changes
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'src/db/pdq.npgsql/**'
            db:
              - 'src/db/pdq.db.common/**'
            npgsql:
              - 'src/db/pdq.npgsql/**'
    outputs:
      run-core: ${{ steps.changes.outputs.core }}
      run-db: ${{ steps.changes.outputs.db }}
      run-npgsql: ${{ steps.changes.outputs.npgsql }}

  pub-pdq:
    name: Pub pdq
    needs: [check-paths]
    if: needs.check-paths.outputs.run-core == 'true'
    uses: daniel-buchanan/pdq/.github/workflows/publish-pdq.yml@main
    secrets: inherit

  pub-pdqdb:
    name: Pub pdq.db
    needs: [check-paths]
    if: needs.check-paths.outputs.run-db == 'true'
    uses: daniel-buchanan/pdq/.github/workflows/publish-pdq.db.yml@main
    secrets: inherit

  pub-pdqnpgsql:
    name: Pub pdq.npgsql
    needs: [check-paths]
    if: needs.check-paths.outputs.run-npgsql == 'true'
    uses: daniel-buchanan/pdq/.github/workflows/publish-pdq.db.npgsql.yml@main
    secrets: inherit
