name: Main
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Sonar Analysis
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  check-paths:
    runs-on: ubuntu-latest
    needs: [sonar, tests]
    if: ${{ github.event_name != 'pull_request' }}
    name: Check Changes
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            core:
              - 'src/core/**'
            db:
              - 'src/db/pdq.db.common/**'
            npgsql:
              - 'src/db/pdq.npgsql/**'
            sqlserver:
              - 'src/db/pdq.sqlserver/**'
            services:
              - 'src/extensions/pdq.services/**'
            logging_serilog:
              - 'src/extensions/pdq.logging.serilog/**'
    outputs:
      run-core: ${{ steps.changes.outputs.core }}
      run-db: ${{ steps.changes.outputs.db }}
      run-npgsql: ${{ steps.changes.outputs.npgsql }}
      run-sqlserver: ${{ steps.changes.outputs.sqlserver }}
      run-services: ${{ steps.changes.outputs.services }}
      run-logging-serilog: ${{ steps.changes.outputs.logging_serilog }}

  pub-pdq:
    name: pdq
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-core == 'true' }}
    uses: ./.github/workflows/publish-pdq.yml
    secrets: inherit

  pub-pdqdb:
    name: pdq.db
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-db == 'true' }}
    uses: ./.github/workflows/publish-pdq.db.yml
    secrets: inherit

  pub-pdqnpgsql:
    name: pdq.npgsql
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-npgsql == 'true' }}
    uses: ./.github/workflows/publish-pdq.db.npgsql.yml
    secrets: inherit

  pub-pdqsqlserver:
    name: pdq.sqlserver
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-sqlserver == 'true' }}
    uses: ./.github/workflows/publish-pdq.db.sqlserver.yml
    secrets: inherit

  pub-pdqservices:
    name: pdq.services
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-services == 'true' }}
    uses: ./.github/workflows/publish-pdq.services.yml
    secrets: inherit
  
  pub-pdqloggingserilog:
    name: pdq.logging.serilog
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.run-logging-serilog == 'true' }}
    uses: ./.github/workflows/publish-pdq.logging.serilog.yml
    secrets: inherit
