name: Publish
on:
  workflow_call:
jobs:
  pack:
    runs-on: ubuntu-latest
    name: Pack
    steps:
      - uses: actions/checkout@v2
      - name: Pack
        env:
          PACKAGE_VERSION: ${{ format('0.1.{0}+{1}', github.run_number, github.sha) }}
          CSPROJ: src/db/pdq.db.common/pdq.db.common-nuget.csproj
        run: |
          dotnet add ${CSPROJ} package pdq.${LATEST_PDQ}
          dotnet build ${CSPROJ} -C Release
          dotnet pack ${CSPROJ} -c Release -p:Version=$PACKAGE_VERSION -o ./output
      - name: Save Archive
        uses: actions/upload-artifact@v2.2.4
        with:
          name: package
          path: ./output
          retention-days: 0

  publish:
    runs-on: ubuntu-latest
    needs: [pack]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: package
        path: ./output
    - name: Upload to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PACKAGE_NAME: ${{ format('pdq.db.0.1.{0}+{1}.nupkg', github.run_number, github.sha) }}
      run: |
        dotnet nuget push ./output/$PACKAGE_NAME \
          -k $NUGET_API_KEY \
          -s https://api.nuget.org/v3/index.json
    - name: Persist Latest Version
      env:
        PACKAGE_VERSION: ${{ format('0.1.{0}+{1}', github.run_number, github.sha) }}
      uses: UnlyEd/github-action-store-variable@v3.0.12
      with:
        # Write variable: `VAR=VALUE` | Read variable: `VAR`
        variables: LATEST_DB=PACKAGE_VERSION
        failIfNotFound: false

