name: Run Tests
on:
  workflow_call:
jobs:
  check-paths:
    runs-on: ubuntu-latest
    name: Check Changes
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            core:
              - 'src/core/**'
            db:
              - 'src/db/pdq.db.common/**'
            npgsql:
              - 'src/db/pdq.npgsql/**'
            sqlserver:
              - 'src/db/pdq.sqlserver/**'
            services:
              - 'src/extensions/pdq.services/**'
            logging:
              - 'src/extensions/pdq.logging.serilog/**'
    outputs:
      run-core: ${{ steps.changes.outputs.core }}
      run-db: ${{ steps.changes.outputs.db }}
      run-services: ${{ steps.changes.outputs.services }}
      run-npgsql: ${{ steps.changes.outputs.npgsql }}
      run-sqlserver: ${{ steps.changes.outputs.sqlserver }}
      run-logging: ${{ steps.changes.outputs.logging }}

  test-pdq:
    needs: [check-paths]
    name: test-pdq
    if: ${{ needs.check-paths.outputs.run-core == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: pdq.core
      test-project: tests/pdq.core-tests/pdq.core-tests.csproj

  test-pdqdb:
    needs: [check-paths]
    name: test-pdqdb
    if: ${{ needs.check-paths.outputs.run-db == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: pdq.db.common
      test-project: tests/pdq.db.common.tests/pdq.db.common.tests.csproj
  
  test-pdqservices:
    needs: [check-paths]
    name: test-pdqservices
    if: ${{ needs.check-paths.outputs.run-services == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: pdq.services
      test-project: tests/pdq.services.tests/pdq.services.tests.csproj

  test-pdqnpgsql:
    needs: [check-paths]
    name: test-pdqnpgsql
    if: ${{ needs.check-paths.outputs.run-npgsql == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: pdq.npgsql
      test-project: tests/pdq.npgsql.tests/pdq.npgsql.tests.csproj

  test-pdqsqlserver:
    needs: [check-paths]
    name: test-pdqsqlserver
    if: ${{ needs.check-paths.outputs.run-sqlserver == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: pdq.sqlserver
      test-project: tests/pdq.sqlserver.tests/pdq.sqlserver.tests.csproj
  test-pdqlogging:
    needs: [check-paths]
    name: test-pdqlogging
    if: ${{ needs.check-paths.outputs.run-logging == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: pdq.logging.serilog
      test-project: tests/pdq.logging.tests/pdq.logging.tests.csproj