name: Run Tests
on:
  workflow_call:
jobs:
  check-paths:
    runs-on: ubuntu-latest
    name: Check Changes
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            core:
              - 'src/core/**'
            db:
              - 'src/db/decaf.db.common/**'
            npgsql:
              - 'src/db/decaf.npgsql/**'
            sqlserver:
              - 'src/db/decaf.sqlserver/**'
            sqlite:
              - 'src/db/decaf.sqlite/**'
            services:
              - 'src/extensions/decaf.services/**'
            logging:
              - 'src/extensions/decaf.logging.serilog/**'
    outputs:
      run-core: ${{ steps.changes.outputs.core }}
      run-db: ${{ steps.changes.outputs.db }}
      run-services: ${{ steps.changes.outputs.services }}
      run-npgsql: ${{ steps.changes.outputs.npgsql }}
      run-sqlserver: ${{ steps.changes.outputs.sqlserver }}
      run-sqlite: ${{ steps.changes.outputs.sqlite }}
      run-logging: ${{ steps.changes.outputs.logging }}

  test-decaf:
    needs: [check-paths]
    name: test-decaf
    if: ${{ needs.check-paths.outputs.run-core == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.core
      test-project: tests/decaf.core.tests/decaf.core.tests.csproj

  test-decafdb:
    needs: [check-paths]
    name: test-decafdb
    if: ${{ needs.check-paths.outputs.run-db == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.db.common
      test-project: tests/decaf.db.common.tests/decaf.db.common.tests.csproj
  
  test-decafservices:
    needs: [check-paths]
    name: test-decafservices
    if: ${{ needs.check-paths.outputs.run-services == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.services
      test-project: tests/decaf.services.tests/decaf.services.tests.csproj

  test-decafnpgsql:
    needs: [check-paths]
    name: test-decafnpgsql
    if: ${{ needs.check-paths.outputs.run-npgsql == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.npgsql
      test-project: tests/decaf.npgsql.tests/decaf.npgsql.tests.csproj

  test-decafsqlserver:
    needs: [check-paths]
    name: test-decafsqlserver
    if: ${{ needs.check-paths.outputs.run-sqlserver == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.sqlserver
      test-project: tests/decaf.sqlserver.tests/decaf.sqlserver.tests.csproj

  test-decafsqlite:
    needs: [check-paths]
    name: test-decafsqlite
    if: ${{ needs.check-paths.outputs.run-sqlite == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.sqlite
      test-project: tests/decaf.sqlite.tests/decaf.sqlite.tests.csproj
  
  test-decaflogging:
    needs: [check-paths]
    name: test-decaflogging
    if: ${{ needs.check-paths.outputs.run-logging == 'true' }}
    uses: ./.github/workflows/test-run.yml
    secrets: inherit
    with:
      job-name: decaf.logging.serilog
      test-project: tests/decaf.logging.tests/decaf.logging.tests.csproj